Lemon-Framework/Lemon

- README.md
- composer.json
- lemon/kernel/builder.php
- lemon/kernel/server.php
- lemon/routing/routes.php
- lemon/views/views.php
Views folder fix
Composer removed "," on end of scripts
> Views, composer changes

- .gitignore
- README.md
- lemon/kernel/Builders/builder.php
- lemon/kernel/Builders/licenses.php
- lemon/kernel/Builders/templates.php
- lemon/kernel/Helpers/commands.php
- lemon/kernel/Helpers/helpers.php
- lemon/kernel/Helpers/info.php
- lemon/kernel/Server/server.php
Fixed gitignore problem with Lemonade kernel
> Lemonade kernel hotfix

- README.md
- lemon/kernel/Lemonade/Helpers/info.php
- lemon/routing/routes.php
Fixed relative routes (won't throw 404)
Relative routes are now as <var>
> 2.1.1-Fixed relative routes

- README.md
- lemon/routing/routes.php
Routing:
-Different callback for each route method
example:
```php
Route::get("/", function()
{
echo "You used get method!;
});
Route::post("/", function()
{
echo "You used post method!";
});
```
-New dynamic route syntax: <> -> {}
example:
```php
Route::get("/dynamic/{var}", function($var)
{
echo $var;
});
```
README
-changed docs link
> 2.2.0 Changed routing architecture 

- README.md
- src/Exceptions/ViewException.php
- src/Http/Routing/Dispatcher.php
- src/Kernel/loader.php
- src/Views/Tag.php
- src/Views/View.php
- src/Views/ViewCompiler.php
- src/Views/views.php
2.4.0 Comes with new templating core
> New templating core

- README.md
- src/Kernel/Application.php
- src/Kernel/Lemonade/Builders/templates.php
Added booter that makes project executing way simpler.
> 2.4.2 Booter

- README.md
- src/Exceptions/ViewException.php
- src/Kernel/Application.php
Fixed ViewException, view folder, directory separator
> 2.4.3 Fixed small view bugs

- README.md
- src/Kernel/Application.php
- src/Kernel/Lemonade/Helpers/commands.php
- src/Kernel/Lemonade/Helpers/info.php
- src/Kernel/Lemonade/Repl/repl.php
> 2.4.4 Lemon repl, booter bugfix

- README.md
- composer.json
- src/Http/Routing/RouteCore.php
- src/Kernel/Application.php
- src/Utils/Env.php
- src/Utils/page.php
- src/Utils/utils.php
Added `Route::controller` which  creates routes for all controller methods named like request methods
Fixed booter and small bugs
> Add: Route controller method Fix: booter

- README.md
- src/Http/Routing/Route.php
- src/Http/Routing/RouteCore.php
- src/Http/Routing/RouteGroup.php
Added ability to group routes created using Route::controller
> 2.6.3 Route controller grouping

- README.md
- src/Http/MiddlewareKernel.php
- src/Http/Routing/Route.php
Middlewares support returning response
> Moved middleware handling to MiddlewareKernel

- src/Http/MiddlewareCollection.php
- src/Http/Routing/Dispatcher.php
- src/Http/Routing/Route.php
- src/Http/Routing/RouteCore.php
MiddlewareKernel renamed to MiddlewareCollection
Added Route Controller resources
Typing `/` in dynamic route is considered as different route
> 2.6.5 MiddlewareCollection, Route Resources

- src/Http/MiddlewareCollection.php
- src/Http/Response.php
- src/Http/Routing/Helpers.php
- src/Http/Routing/RouteCore.php
- src/Http/Routing/RouteGroup.php
> :recycle: refactors away from usages of get_class and gettype

- src/Lemon/Http/Request.php
- src/Lemon/Testing/TestCase.php
- tests/Http/Middlewares/CorsTest.php
- tests/Http/RequestTest.php
- tests/Protection/CsrfTest.php
- tests/Routing/MiddlewareTest.php
- tests/Routing/RouterTest.php
This PR adds Request::ip() which returns ip address. Be careful when using.
> adds Request::ip()

- src/Lemon/Templating/Template.php
- src/Lemon/Testing/TestResponse.php
- tests/Testing/TestCase.php
- tests/Testing/TestResponseTest.php
This PR adds testing of template data, which is useful in testing of errors.
> [Testing ]added template data testing

- src/Lemon/Testing/TestResponse.php
- tests/Testing/TestCase.php
- tests/Testing/TestResponseTest.php
This PR fixes template data testing, now we have to provide all expected values.
> [Testing] fixes data testing

- src/Lemon/Testing/TestResponse.php
- tests/Testing/TestCase.php
- tests/Testing/TestResponseTest.php
Reverts Lemon-Framework/Lemon#108
> Revert "[Testing] fixes data testing"

- src/Lemon/Debug/Handling/Consultant.php
- src/Lemon/Debug/Handling/Reporter.php
- src/Lemon/Debug/Handling/TerminalReporter.php
- src/Lemon/Debug/Handling/templates/reporter.phtml
- storage/logs/.gitignore
- tests/Debug/ConsultantTest.php
This PR adds links to documentation depending on error class, meaning that if you get for example CacheException, it would give you link to cache docs.
> [Consultant] documentation links

- src/Lemon/Kernel/Application.php
- src/Lemon/Kernel/Commands.php
- src/Lemon/Kernel/templates/help.phtml
- src/Lemon/Terminal/IO/Html/Components.php
- storage/logs/.gitignore
This PR adds version command along with some minor terminal fixes.
> [Terminal] adds version command

- src/Lemon/Event.php
- src/Lemon/Events/Dispatcher.php
This PR adds Dispatcher::when, which is just alias to Dispatcher::on, but more declarative I guess.
> [Event] adds Dispatcher::when

- src/Lemon/Validation/Rules.php
- tests/Validation/RulesTest.php
> Add numeric comparison and years rules
